# Generated by Django 4.0.2 on 2022-10-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_afganistan_africana_argentina_austria_belgica_brunei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afganistan',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='afganistan',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/afganistan'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='africana',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/africana'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='argentina',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/argentina'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='austria',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/austria'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='belgica',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/belgica'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='brunei',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/brunei'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='caboverde',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/caboverde'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='canada',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/canada'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='catar',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/catar'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='corea',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/corea'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='croacia',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/croacia'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='cuba',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/cuba'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='egipto',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/egipto'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='espana',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/espana'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='etiopia',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/etiopia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='grecia',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/grecia'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='guatemala',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/guatemala'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='hungria',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/hungria'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='indonesia',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/indonesia'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='kuwait',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/kuwait'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='lituania',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/lituania'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='sanmarino',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/sanmarino'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='suiza',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/suiza'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='turquia',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/turquia'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='uzbekistan',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/uzbekistan'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='venezuela',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/venezuela'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos1',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos10',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos2',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos3',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos4',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos5',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos6',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos7',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos8',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
        migrations.AlterField(
            model_name='yemen',
            name='fotos9',
            field=models.ImageField(blank=True, upload_to='Fotos/yemen'),
        ),
    ]
